name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          pip install -e .[dev]
      - name: Ruff
        run: ruff check vgj_chat tests
      - name: Black
        run: black --check vgj_chat/config.py tests
      - name: Pytest
        run: pytest -q
